name: "easy-python-version"

description: "Replaces __version__ in your __init__.py with that found in VCS"

branding:
  color: red
  icon: git-branch

inputs:

  init_path:
    description: |
      Path, relative to the root directory of your respository, to the
      __init__.py file of your project.
    required: true 


runs: 

  using: composite
  steps:

    - name: Install python 
      uses: actions/setup-python@v2
      with:
        python-version: "3.9" 

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch version
      uses: mtkennerly/dunamai-action@v1.3.0
      with:
        env-var: MY_VERSION
        args: --style pep440 --no-metadata

    - name: Print verion
      shell: bash
      run: echo "$MY_VERSION"

    - name: Replace verion in __init__.py 
      shell: bash
      run: bash action.sh
      env:
        ACTION_PATH: ${{ github.action_path }}
        INIT_PATH: ${{ inputs.init_path }}
        VERSION: ${{ MY_VERSION }}
