name: "easy-python-version"

description: "Replaces __version__ in your __init__.py with that found in VCS"

branding:
  color: red
  icon: git-branch

inputs:

  package_path:
    description: |
      Path, relative to the root directory of your respository, to the Python
      package, to which `__version__.py` will be written.
    required: true 

  on_tag_push_only:
    description: |
      If true, will only run on tagged commits that are also push events 
      (this is the intended behavior).
    required: false
    default: true
    
runs: 

  using: composite
  steps:

    - name: Install python 
      uses: actions/setup-python@v2
      with:
        python-version: "3.9" 

    - name: Fetch version
      uses: mtkennerly/dunamai-action@v1.3.0
      with:
        env-var: MY_VERSION
        args: --style pep440 --no-metadata

    - name: Print verion
      shell: bash
      run: echo "$MY_VERSION"

    - name: Write __version__.py 
      shell: bash
      if: (! inputs.on_tag_push_only) || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags'))
      run: bash action.sh
      env:
        ACTION_PATH: ${{ github.action_path }}
        PACKAGE_PATH: ${{ inputs.package_path }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
