name: test

on:
  - push
  - pull_request

jobs:

  test:

    strategy:
      matrix:
        os: [ubuntu-latest] 
    runs-on: ${{ matrix.os }}

    steps:
      - name: "test self"
        uses: ./
